### ISSUE TITLE
Error in tensorflowjs

### ISSUE THREAD

**Issue by alwargaurav** [GauravScripts/Dispatch-Dynamo#2]
Error: node_modules/@tensorflow/tfjs-core/dist/hash_util.d.ts:4:49 - error TS2304: Cannot find name 'Long'.

4 export declare function hexToLong(hex: string): Long;

Error: node_modules/@tensorflow/tfjs-core/dist/hash_util.d.ts:5:69 - error TS2304: Cannot find name 'Long'.

5 export declare function fingerPrint64(s: Uint8Array, len?: number): Long;

**Comment by GauravScripts** [comment]
import * as Long from "long"; in hash_util.d.ts

**Comment by alwargaurav** [comment]
ok
